'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'vi' | 'en' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('vi');

  useEffect(() => {
    const saved = localStorage.getItem('language');
    if (saved === 'en' || saved === 'vi' || saved === 'ko') {
      setLanguageState(saved);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations: Record<Language, any> = {
  vi: {
    nav: {
      home: 'Trang chủ',
      products: 'Sản phẩm',
      cart: 'Giỏ hàng',
      myAccount: 'Tài khoản',
      login: 'Đăng nhập',
      logout: 'Đăng xuất',
    },
    home: {
      hero: {
        title: 'KYGO PROM',
        subtitle: 'Thuê & Mua Đầm Dạ Hội Cao Cấp',
        description: 'Khám phá bộ sưu tập váy đầm dạ hội sang trọng, thanh lịch. Dịch vụ cho thuê linh hoạt 1-3 ngày với giá ưu đãi.',
        exploreNow: 'Khám phá ngay',
        rentDress: 'Thuê váy',
      },
      sections: {
        occasions: 'Dịp Mặc',
        styles: 'Phong Cách',
        newArrivals: 'Hàng Mới Về',
        trending: 'Xu Hướng Hiện Hành',
      },
      features: {
        quality: {
          title: 'Sản phẩm chất lượng cao',
          desc: '100% váy chính hãng, nhập khẩu',
        },
        delivery: {
          title: 'Giao hàng nhanh chóng',
          desc: 'Giao hàng toàn quốc, nhanh trong ngày',
        },
        price: {
          title: 'Giá cả hợp lý',
          desc: 'Cho thuê từ 1-3 ngày với giá ưu đãi',
        },
        support: {
          title: 'Hỗ trợ tận tâm',
          desc: 'Tư vấn nhiệt tình, chuyên nghiệp',
        },
      },
    },
    products: {
      buy: 'Hàng',
      rentDN: 'Thuê ĐN',
      rentProvince: 'Thuê Tỉnh',
      freeRental: 'Thuê 0đ khi mua gói ưu đãi',
      rentPerTime: 'Giá thuê/ 1 lần',
      rentPerDay: 'Giá thuê/ngày',
      extraDayNote: 'Tính 10% cho các ngày kế tiếp',
      deposit: 'Tiền cọc',
      depositInfo: 'Tiền cọc (thanh toán khi nhận)',
      overLimitWarning: 'Lưu ý: Thời gian thuê vượt quá 3 ngày',
      extraDayFee: 'Phụ phí ngày vượt (10%/ngày)',
      rentalPeriod: 'Thời gian thuê',
      pickupDate: 'Ngày nhận',
      returnDate: 'Ngày trả',
      selectStartDate: 'Chọn ngày bắt đầu thuê',
      selectEndDate: 'Chọn ngày kết thúc thuê',
      maxDays: 'Khuyến nghị tối đa 3 ngày',
      totalRentalFee: 'Tổng tiền thuê',
      depositFee: 'Tiền cọc',
      totalAmountDue: 'Tổng tiền phải trả',
    },
    productDetail: {
      brand: 'Thương hiệu',
      productCode: 'Mã sản phẩm',
      occasion: 'Dịp dùng',
      addToCart: 'Thêm vào giỏ',
      buyNow: 'Mua ngay',
      rentNow: 'Thuê ngay',
      description: 'Mô tả sản phẩm',
      specifications: 'Thông số',
      reviews: 'Đánh giá',
      additionalInfo: 'Thông tin bổ sung',
      reviewsCount: 'Đánh giá (0)',
      similarProducts: 'Sản phẩm tương tự',
      occasions: 'Dịp mặc',
      style: 'Phong cách',
      size: 'Size',
      color: 'Màu sắc',
      category: 'Danh mục',
      rentDress: 'Thuê váy',
      buyDress: 'Mua váy',
      selectSize: 'Chọn size',
      selectColor: 'Màu sắc',
    },
    cart: {
      emptyCart: 'Giỏ hàng trống',
      noItems: 'Bạn chưa có sản phẩm nào trong giỏ hàng',
      continueShopping: 'Tiếp tục mua sắm',
      cartTitle: 'Giỏ hàng',
      proceedToCheckout: 'Tiến hnh thanh toán',
      removeItem: 'Xóa sản phẩm',
      rentalDate: 'Ngày thuê',
      returnDate: 'Ngày trả',
      duration: 'Thời gian',
      size: 'Size',
      rent: 'Thuê',
      buy: 'Mua',
      rentalPrice: 'Giá thuê',
      price: 'Giá',
      depositFee: 'Tiền cọc',
      subtotal: 'Tạm tính',
      total: 'Tổng cộng',
      orderSummary: 'Tóm tắt đơn hàng',
      freeShipping: 'Miễn phí vận chuyển nội thành',
      depositRefund: 'Hoàn tiền cọc trong 48h sau khi trả váy',
      freeSizeChange: 'Hỗ trợ đổi size miễn phí',
      applyDiscount: 'Áp dụng mã giảm giá',
      discountCode: 'Mã giảm giá',
      apply: 'Áp dụng',
      depositMethod: 'Phương thức cọc',
      cashDeposit: 'Cọc bằng tiền mặt',
      idCardDeposit: 'Cọc bằng Giấy tờ tùy thân',
      rentalPeriod: 'Thời gian thuê',
      pickupTime: 'Nhận hàng',
      returnTime: 'Trả hàng',
    },
    checkout: {
      title: 'Thanh toán',
      customerInfo: 'Thông tin khách hàng',
      deliveryInfo: 'Thông tin giao hàng',
      paymentMethod: 'Phương thức thanh toán',
      placeOrder: 'Đặt hàng',
    },
    footer: {
      about: 'Giới thiệu',
      support: 'Hỗ trợ mua & thuê hàng',
      policies: 'Chính sách',
      contact: 'Liên hệ',
      followUs: 'Kết nối với chúng tôi',
      copyright: 'Tất cả quyền được bảo lưu',
    },
    filter: {
      category: 'Danh mục sản phẩm',
      occasion: 'Dịp mặc',
      style: 'Phong cách',
      color: 'Màu sắc',
      colorPlaceholder: 'Ví dụ: đỏ, trắng…',
      size: 'Size',
      price: 'Giá',
      type: 'Loại',
      all: 'Tất cả',
      rent: 'Thuê',
      buy: 'Mua',
      under5m: 'Dưới 5 triệu',
      from5to10m: '5 - 10 triệu',
      above10m: 'Trên 10 triệu',
    },
    listing: {
      searchNameOrCode: 'Tên hoặc mã váy',
      breadcrumbHome: 'Trang chủ',
      breadcrumbProducts: 'Sản phẩm',
      sortNewest: 'Mới nhất',
      sortPopular: 'Bán chạy',
      sortPriceAsc: 'Giá từ thấp đến cao',
      sortPriceDesc: 'Giá từ cao đến thấp',
      filterBtn: 'Bộ lọc',
      showingProducts: 'Hiển thị',
      products: 'sản phẩm',
      noResults: 'Không tìm thấy sản phẩm phù hợp',
      categories: {
        all: 'Tất cả sản phẩm',
        princessDresses: 'Đầm công chúa',
        featherDresses: 'Đầm lông',
        setDresses: 'Đầm set bộ',
        luxuryEmbellished: 'Đầm luxury đính đá',
        midiDresses: 'Đầm midi',
        trainDresses: 'Đầm có tà',
        shortDresses: 'Đầm ngắn',
        sequinDresses: 'Đầm bling sequin',
        eveningGowns: 'Đầm dạ hội',
      },
      occasions: {
        office: 'Công sở',
        evening: 'Dạ hội',
        party: 'Dự tiệc',
        contest: 'Cuộc thi',
        wedding: 'Đám cưới',
        dating: 'Hẹn hò – dạo phố',
      },
      styles: {
        unique: 'Cá tính',
        princess: 'Công chúa',
        sexy: 'Gợi cảm',
        dynamic: 'Năng động',
        elegant: 'Thanh lịch',
        standout: 'Nổi bật',
      },
    },
    common: {
      perDay: '/ngày',
      days: 'ngày',
      viewAll: 'Xem tất cả',
      viewDetails: 'Xem chi tiết',
      search: 'Tìm kiếm',
      sort: 'Sắp xếp',
      filter: 'Lọc',
      apply: 'Áp dụng',
      cancel: 'Hủy',
      confirm: 'Xác nhận',
      close: 'Đóng',
      save: 'Lưu',
      edit: 'Chỉnh sửa',
      delete: 'Xóa',
      loading: 'Đang tải...',
      error: 'Lỗi',
      success: 'Thành công',
      backToHome: 'Về trang chủ',
    },
    styleTips: {
      title: 'Bí Quyết Mặc Đẹp',
      subtitle: 'Cẩm nang thời trang váy dạ hội - Những mẹo và xu hướng mới nhất để bạn luôn tỏa sáng',
      featured: 'Nổi bật',
      minRead: 'phút đọc',
      readMore: 'Đọc tiếp',
      notFound: 'Không tìm thấy bài viết',
      backToList: 'Quay lại danh sách',
      share: 'Chia sẻ',
      linkCopied: 'Đã sao chép liên kết!',
      tags: 'Thẻ',
      relatedArticles: 'Bài viết liên quan',
    },
    events: {
      title: 'Sự kiện & Hoa khôi',
      subtitle: 'Những khoảnh khắc nổi bật cùng Kygo Prom',
      searchPlaceholder: 'Tìm kiếm sự kiện hoặc thí sinh...',
      showing: 'Hiển thị',
      events: 'sự kiện',
      noResults: 'Không tìm thấy sự kiện phù hợp',
      dressesUsed: 'váy được sử dụng',
      viewDetails: 'Xem chi tiết',
      kygoSponsored: 'Kygo tài trợ',
      notFound: 'Không tìm thấy sự kiện',
      backToList: 'Quay lại danh sách',
      aboutEvent: 'Về sự kiện',
      organizer: 'Đơn vị tổ chức',
      scale: 'Quy mô',
      gallery: 'Thư viện ảnh',
      photos: 'ảnh',
      contestants: 'Thí sinh nổi bật',
      dress: 'Váy',
      relatedDresses: 'Các mẫu váy được sử dụng',
      relatedDressesDesc: 'Khám phá những mẫu váy dạ hội xuất hiện tại sự kiện này',
      exploreMore: 'Khám phá thêm',
      ctaTitle: 'Bạn muốn tỏa sáng trong sự kiện của mình?',
      ctaDescription: 'Hãy để Kygo Prom đồng hành cùng bạn với những mẫu váy dạ hội sang trọng và dịch vụ chuyên nghiệp',
      ctaExplore: 'Khám phá bộ sưu tập',
      ctaContact: 'Liên hệ tư vấn',
      filters: {
        all: 'Tất cả',
        contest: 'Cuộc thi',
        runway: 'Runway',
        bts: 'Hậu trường',
        sponsored: 'Kygo tài trợ',
      },
    },
  },
  en: {
    nav: {
      home: 'Home',
      products: 'Products',
      cart: 'Cart',
      myAccount: 'My Account',
      login: 'Login',
      logout: 'Logout',
    },
    home: {
      hero: {
        title: 'KYGO PROM',
        subtitle: 'Rent & Buy Premium Evening Gowns',
        description: 'Discover our elegant and luxurious evening gown collection. Flexible rental service for 1-3 days with special prices.',
        exploreNow: 'Explore Now',
        rentDress: 'Rent Dress',
      },
      sections: {
        occasions: 'Occasions',
        styles: 'Styles',
        newArrivals: 'New Arrivals',
        trending: 'Trending Now',
      },
      features: {
        quality: {
          title: 'High Quality Products',
          desc: '100% authentic imported dresses',
        },
        delivery: {
          title: 'Fast Delivery',
          desc: 'Nationwide delivery, same-day service',
        },
        price: {
          title: 'Affordable Prices',
          desc: 'Rent for 1-3 days with special prices',
        },
        support: {
          title: 'Dedicated Support',
          desc: 'Enthusiastic, professional consultation',
        },
      },
    },
    products: {
      buy: 'Buy',
      rentDN: 'Rent DN',
      rentProvince: 'Rent Province',
      freeRental: 'Free rental with package deals',
      rentPerTime: 'Rent Price/ 1 time',
      rentPerDay: 'Rent Price/ day',
      extraDayNote: '10% for each additional day',
      deposit: 'Deposit',
      depositInfo: 'Deposit (paid upon pickup)',
      overLimitWarning: 'Note: Rental period exceeds 3 days',
      extraDayFee: 'Extra day fee (10%/day)',
      rentalPeriod: 'Rental period',
      pickupDate: 'Pickup date',
      returnDate: 'Return date',
      selectStartDate: 'Select start date',
      selectEndDate: 'Select end date',
      maxDays: 'Recommended maximum 3 days',
      totalRentalFee: 'Total Rental Fee',
      depositFee: 'Deposit Fee',
      totalAmountDue: 'Total Amount Due',
    },
    productDetail: {
      brand: 'Brand',
      productCode: 'Product Code',
      occasion: 'Occasion',
      addToCart: 'Add to Cart',
      buyNow: 'Buy Now',
      rentNow: 'Rent Now',
      description: 'Description',
      specifications: 'Specifications',
      reviews: 'Reviews',
      additionalInfo: 'Additional Info',
      reviewsCount: 'Reviews (0)',
      similarProducts: 'Similar Products',
      occasions: 'Occasions',
      style: 'Style',
      size: 'Size',
      color: 'Color',
      category: 'Category',
      rentDress: 'Rent Dress',
      buyDress: 'Buy Dress',
      selectSize: 'Select Size',
      selectColor: 'Select Color',
    },
    cart: {
      emptyCart: 'Empty cart',
      noItems: 'You don\'t have any items in your cart',
      continueShopping: 'Continue shopping',
      cartTitle: 'Shopping cart',
      proceedToCheckout: 'Proceed to checkout',
      removeItem: 'Remove item',
      rentalDate: 'Rental date',
      returnDate: 'Return date',
      duration: 'Duration',
      size: 'Size',
      rent: 'Rent',
      buy: 'Buy',
      rentalPrice: 'Rental price',
      price: 'Price',
      depositFee: 'Deposit fee',
      subtotal: 'Subtotal',
      total: 'Total',
      orderSummary: 'Order summary',
      freeShipping: 'Free shipping in city',
      depositRefund: 'Deposit refund within 48h after return',
      freeSizeChange: 'Free size change support',
      applyDiscount: 'Apply discount code',
      discountCode: 'Discount code',
      apply: 'Apply',
      depositMethod: 'Deposit method',
      cashDeposit: 'Cash deposit',
      idCardDeposit: 'ID card deposit',
      rentalPeriod: 'Rental period',
      pickupTime: 'Pickup',
      returnTime: 'Return',
    },
    checkout: {
      title: 'Checkout',
      customerInfo: 'Customer Information',
      deliveryInfo: 'Delivery Information',
      paymentMethod: 'Payment Method',
      placeOrder: 'Place Order',
    },
    footer: {
      about: 'About Us',
      support: 'Customer Support',
      policies: 'Policies',
      contact: 'Contact',
      followUs: 'Follow Us',
      copyright: 'All rights reserved',
    },
    filter: {
      category: 'Category',
      occasion: 'Occasion',
      style: 'Style',
      color: 'Color',
      colorPlaceholder: 'e.g. red, white…',
      size: 'Size',
      price: 'Price',
      type: 'Type',
      all: 'All',
      rent: 'Rent',
      buy: 'Buy',
      under5m: 'Under 5M',
      from5to10m: '5M - 10M',
      above10m: 'Above 10M',
    },
    listing: {
      searchNameOrCode: 'Name or dress code',
      breadcrumbHome: 'Home',
      breadcrumbProducts: 'Products',
      sortNewest: 'Newest',
      sortPopular: 'Best Sellers',
      sortPriceAsc: 'Price: Low to High',
      sortPriceDesc: 'Price: High to Low',
      filterBtn: 'Filters',
      showingProducts: 'Showing',
      products: 'products',
      noResults: 'No products found',
      categories: {
        all: 'All Products',
        princessDresses: 'Princess Dresses',
        featherDresses: 'Feather Dresses',
        setDresses: 'Set Dresses',
        luxuryEmbellished: 'Luxury Embellished',
        midiDresses: 'Midi Dresses',
        trainDresses: 'Train Dresses',
        shortDresses: 'Short Dresses',
        sequinDresses: 'Sequin Dresses',
        eveningGowns: 'Evening Gowns',
      },
      occasions: {
        office: 'Office',
        evening: 'Evening',
        party: 'Party',
        contest: 'Contest',
        wedding: 'Wedding',
        dating: 'Dating & Street',
      },
      styles: {
        unique: 'Unique',
        princess: 'Princess',
        sexy: 'Sexy',
        dynamic: 'Dynamic',
        elegant: 'Elegant',
        standout: 'Standout',
      },
    },
    common: {
      perDay: '/day',
      days: 'days',
      viewAll: 'View All',
      viewDetails: 'View Details',
      search: 'Search',
      sort: 'Sort',
      filter: 'Filter',
      apply: 'Apply',
      cancel: 'Cancel',
      confirm: 'Confirm',
      close: 'Close',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      backToHome: 'Back to Home',
    },
    styleTips: {
      title: 'Dress Up Tips',
      subtitle: 'Evening gown fashion guide - The latest tips and trends to always shine',
      featured: 'Featured',
      minRead: 'min read',
      readMore: 'Read more',
      notFound: 'No article found',
      backToList: 'Back to list',
      share: 'Share',
      linkCopied: 'Link copied!',
      tags: 'Tags',
      relatedArticles: 'Related articles',
    },
    events: {
      title: 'Events & Beauty Queens',
      subtitle: 'Shining moments with Kygo Prom',
      searchPlaceholder: 'Search events or contestants...',
      showing: 'Showing',
      events: 'events',
      noResults: 'No events found',
      dressesUsed: 'dresses used',
      viewDetails: 'View details',
      kygoSponsored: 'Kygo Sponsored',
      notFound: 'Event not found',
      backToList: 'Back to list',
      aboutEvent: 'About Event',
      organizer: 'Organizer',
      scale: 'Scale',
      gallery: 'Photo Gallery',
      photos: 'photos',
      contestants: 'Featured Contestants',
      dress: 'Dress',
      relatedDresses: 'Dresses Featured',
      relatedDressesDesc: 'Discover the evening gowns showcased at this event',
      exploreMore: 'Explore More',
      ctaTitle: 'Want to shine at your event?',
      ctaDescription: 'Let Kygo Prom accompany you with elegant evening gowns and professional service',
      ctaExplore: 'Explore Collection',
      ctaContact: 'Contact Us',
      filters: {
        all: 'All',
        contest: 'Contest',
        runway: 'Runway',
        bts: 'Behind The Scenes',
        sponsored: 'Kygo Sponsored',
      },
    },
    pagination: {
      previous: 'Previous',
      next: 'Next',
      showing: 'Showing',
      of: 'of',
    },
  },
  ko: {
    nav: {
      home: '홈',
      products: '제품',
      cart: '장바구니',
      myAccount: '내 계정',
      login: '로그인',
      logout: '로그아웃',
    },
    home: {
      hero: {
        title: 'KYGO PROM',
        subtitle: '프리미엄 이브닝 가운 대여 및 구매',
        description: '우아하고 고급스러운 이브닝 가운 컬렉션을 만나보세요. 특별 가격으로 1-3일 유연한 대여 서비스를 제공합니다.',
        exploreNow: '지금 둘러보기',
        rentDress: '드레스 대여',
      },
      sections: {
        occasions: '착용 행사',
        styles: '스타일',
        newArrivals: '신상품',
        trending: '인기 상품',
      },
      features: {
        quality: {
          title: '고품질 제품',
          desc: '100% 정품 수입 드레스',
        },
        delivery: {
          title: '빠른 배송',
          desc: '전국 배송, 당일 서비스',
        },
        price: {
          title: '합리적인 가격',
          desc: '특별 가격으로 1-3일 대여',
        },
        support: {
          title: '친절한 지원',
          desc: '정적이고 전문적인 상담',
        },
      },
    },
    products: {
      buy: '구매',
      rentDN: '다낭 대여',
      rentProvince: '지방 대여',
      freeRental: '패키지 구매 시 무료 대여',
      rentPerTime: '대여 가격/ 1회',
      rentPerDay: '대여 가격/ 일',
      extraDayNote: '추가 일당 10%',
      deposit: '보증금',
      depositInfo: '보증금 (수령 시 지불)',
      overLimitWarning: '주의: 대여 기간이 3일을 초과했습니다',
      extraDayFee: '추가 일당 (10%/일)',
      rentalPeriod: '대여 기간',
      pickupDate: '수령일',
      returnDate: '반납일',
      selectStartDate: '대여 시작일 선택',
      selectEndDate: '대여 종료일 선택',
      maxDays: '최대 3일 권장',
      totalRentalFee: '총 대여료',
      depositFee: '보증금',
      totalAmountDue: '총 결제 금액',
    },
    productDetail: {
      brand: '브랜드',
      productCode: '제품 코드',
      occasion: '사용 행사',
      addToCart: '장바구니에 담기',
      buyNow: '바로 구매',
      rentNow: '바로 대여',
      description: '상품 설명',
      specifications: '상품 정보',
      reviews: '리뷰',
      additionalInfo: '추가 정보',
      reviewsCount: '리뷰 (0)',
      similarProducts: '유사 제품',
      occasions: '행사',
      style: '스타일',
      size: '사이즈',
      color: '색상',
      category: '카테고리',
      rentDress: '드레스 대여',
      buyDress: '드레스 구매',
      selectSize: '사이즈 선택',
      selectColor: '색상 선택',
    },
    cart: {
      emptyCart: 'Empty cart',
      noItems: 'You don\'t have any items in your cart',
      continueShopping: 'Continue shopping',
      cartTitle: 'Shopping cart',
      proceedToCheckout: 'Proceed to checkout',
      removeItem: 'Remove item',
      rentalDate: 'Rental date',
      returnDate: 'Return date',
      duration: 'Duration',
      size: 'Size',
      rent: 'Rent',
      buy: 'Buy',
      rentalPrice: 'Rental price',
      price: 'Price',
      depositFee: 'Deposit fee',
      subtotal: 'Subtotal',
      total: 'Total',
      orderSummary: 'Order summary',
      freeShipping: 'Free shipping in city',
      depositRefund: 'Deposit refund within 48h after return',
      freeSizeChange: 'Free size change support',
      applyDiscount: 'Apply discount code',
      discountCode: 'Discount code',
      apply: 'Apply',
      depositMethod: 'Deposit method',
      cashDeposit: 'Cash deposit',
      idCardDeposit: 'ID card deposit',
      rentalPeriod: 'Rental period',
      pickupTime: 'Pickup',
      returnTime: 'Return',
    },
    checkout: {
      title: '결제',
      customerInfo: '고객 정보',
      deliveryInfo: '배송 정보',
      paymentMethod: '결제 방법',
      placeOrder: '주문하기',
    },
    footer: {
      about: '회사 소개',
      support: '고객 지원',
      policies: '정책',
      contact: '연락처',
      followUs: '팔로우',
      copyright: '모든 권리 보유',
    },
    filter: {
      category: '카테고리',
      occasion: '행사',
      style: '스타일',
      color: '색상',
      colorPlaceholder: '예: 빨강, 흰색…',
      size: '사이즈',
      price: '가격',
      type: '유형',
      all: '전체',
      rent: '대여',
      buy: '구매',
      under5m: '5백만 미만',
      from5to10m: '5백만 - 1천만',
      above10m: '1천만 이상',
    },
    listing: {
      searchNameOrCode: '이름 또는 드레스 코드',
      breadcrumbHome: '홈',
      breadcrumbProducts: '제품',
      sortNewest: '최신순',
      sortPopular: '인기순',
      sortPriceAsc: '가격: 낮은순',
      sortPriceDesc: '가격: 높은순',
      filterBtn: '필터',
      showingProducts: '표시',
      products: '제품',
      noResults: '일치하는 제품이 없습니다',
      categories: {
        all: '모든 제품',
        princessDresses: '프린세스 드레스',
        featherDresses: '페더 드레스',
        setDresses: '세트 드레스',
        luxuryEmbellished: '럭셔리 장식',
        midiDresses: '미디 드레스',
        trainDresses: '트레인 드레스',
        shortDresses: '짧은 드레스',
        sequinDresses: '시퀸 드레스',
        eveningGowns: '이브닝 가운',
      },
      occasions: {
        office: '사무실',
        evening: '이브닝',
        party: '파티',
        contest: '대회',
        wedding: '결혼식',
        dating: '데이트 & 산책',
      },
      styles: {
        unique: '개성있는',
        princess: '공주',
        sexy: '섹시',
        dynamic: '활동적',
        elegant: '우아한',
        standout: '돋보이는',
      },
    },
    common: {
      perDay: '/일',
      days: '일',
      viewAll: '모두 보기',
      viewDetails: '상세보기',
      search: '검색',
      sort: '정렬',
      filter: '필터',
      apply: '적용',
      cancel: '취소',
      confirm: '확인',
      close: '닫기',
      save: '저장',
      edit: '편집',
      delete: '삭제',
      loading: '로딩 중...',
      error: '오류',
      success: '성공',
      backToHome: '홈으로',
    },
    styleTips: {
      title: '드레스 업 팁',
      subtitle: '이브닝 가운 패션 가이드 - 항상 빛나는 최신 팁과 트렌드',
      featured: '추천',
      minRead: '분 읽기',
      readMore: '더 읽기',
      notFound: '게시글을 찾을 수 없습니다',
      backToList: '목록으로 돌아가기',
      share: '공유',
      linkCopied: '링크 복사됨!',
      tags: '태그',
      relatedArticles: '관련 게시글',
    },
    events: {
      title: 'Events & Beauty Queens',
      subtitle: 'Shining moments with Kygo Prom',
      searchPlaceholder: 'Search events or contestants...',
      showing: 'Showing',
      events: 'events',
      noResults: 'No events found',
      dressesUsed: 'dresses used',
      viewDetails: 'View details',
      kygoSponsored: 'Kygo Sponsored',
      notFound: 'Event not found',
      backToList: 'Back to list',
      aboutEvent: 'About Event',
      organizer: 'Organizer',
      scale: 'Scale',
      gallery: 'Photo Gallery',
      photos: 'photos',
      contestants: 'Featured Contestants',
      dress: 'Dress',
      relatedDresses: 'Dresses Featured',
      relatedDressesDesc: 'Discover the evening gowns showcased at this event',
      exploreMore: 'Explore More',
      ctaTitle: 'Want to shine at your event?',
      ctaDescription: 'Let Kygo Prom accompany you with elegant evening gowns and professional service',
      ctaExplore: 'Explore Collection',
      ctaContact: 'Contact Us',
      filters: {
        all: 'All',
        contest: 'Contest',
        runway: 'Runway',
        bts: 'Behind The Scenes',
        sponsored: 'Kygo Sponsored',
      },
    },
    pagination: {
      previous: '이전',
      next: '다음',
      showing: '표시',
      of: '/',
    },
  },
};